//! Command line shell over `colophon-core`.

use anyhow::{Context, Result};
use clap::Parser;
use colophon_core::{build_album, format, pdf, Album, BuildOptions};
use std::path::PathBuf;

/// Colophon: from a folder of photos to a print-ready album.
#[derive(Parser)]
#[command(name = "colophon", version, about)]
#[command(after_help = FORMAT_HELP.as_str())]
struct Cli {
    /// Folder of photos to build the album from
    #[arg(required_unless_present_any = ["formats", "profils", "profils_json", "dump_geometry", "dump_scene", "print", "cover", "audit", "reprise", "prevol", "sheets", "proposition", "gabarits", "banc_gabarits", "depuis_fiches"])]
    photos: Option<PathBuf>,

    /// Output directory (album.json, album.pdf, thumbnail cache)
    #[arg(short, long, default_value = "album-out")]
    out: PathBuf,

    /// Album title (defaults to the folder name)
    #[arg(short, long)]
    title: Option<String>,

    /// Target number of spreads (double pages) for the finished album
    #[arg(short, long, default_value_t = 48)]
    spreads: usize,

    /// Page format: a preset name, or LARGEURxHAUTEUR in millimetres
    #[arg(short, long, default_value = "carre-21")]
    format: String,

    /// Composition pace: aeree, equilibree, dense. Same photos and the same
    /// rules; how many of them land on a spread, and how many pages the
    /// album ends up with.
    #[arg(long, default_value = "equilibree", value_name = "PACE")]
    densite: String,

    /// Compose the two alternative proposals beside the album, the way the
    /// app does. They land next to it as `album.<id>.json`; the audit gate
    /// reads them one by one.
    #[arg(long)]
    variantes: bool,

    /// Write the folder's relevé to FICHIER: what the scan and the analysis
    /// measured, and nothing else. The reading half of a composition is the
    /// only one that touches a pixel; these fiches carry everything the
    /// other half needs, so the same album can be composed on a machine
    /// that holds no photograph. Regenerated by scripts/fiches.sh.
    #[arg(long, value_name = "FICHIER")]
    dump_fiches: Option<PathBuf>,

    /// Compose from a relevé instead of a folder of photos. Writes
    /// album.json, album.origin.json, curation.json, the variantes and the
    /// relevé the linter measures; no thumbnails, no PDF, no cover, there
    /// being no pixel to read.
    #[arg(long, value_name = "FICHIER")]
    depuis_fiches: Option<PathBuf>,

    /// List the available page formats and exit
    #[arg(long)]
    formats: bool,

    /// Print every template's slot geometry as JSON and exit. Feeds the
    /// parity check against the editor's TypeScript port.
    #[arg(long)]
    dump_geometry: bool,

    /// Print the scene of every spread as JSON and exit: what each spread
    /// actually holds, as objects, in paint order. The committed fixture of
    /// the parity check is this output, and so is what a renderer is
    /// compared against.
    ///
    /// Reads `album.json` from --out, or the file given here. `--format`
    /// applies: the same spreads are re-derived at that page shape, which is
    /// how one committed album covers the six formats without being
    /// recomposed six times.
    #[arg(long, value_name = "ALBUM.JSON", num_args = 0..=1, default_missing_value = "")]
    dump_scene: Option<String>,

    /// Bleed of the dumped geometry, in millimetres. The dev album server
    /// asks for the album's own bleed; the format previews ask for none.
    #[arg(long, value_name = "MM", hide = true, default_value_t = 3.0)]
    bleed: f64,

    /// Render album-print.pdf at full resolution (300 dpi) from the album
    /// already built in --out. Reopens the originals: slower than the
    /// preview, and the photo folder must still be in place.
    #[arg(long)]
    print: bool,

    /// Lint the album already built in --out: count the defect classes
    /// (visage coupé, orientation trahie, doublons sur une planche…) and
    /// print the JSON report. Exits non-zero when a counter passes son seuil.
    #[arg(long)]
    audit: bool,

    /// Measure how much of the composer's proposal was corrected by hand:
    /// compares album.json against the album.origin.json written at the
    /// first build. Exits non-zero past 30 % of spreads touched.
    #[arg(long)]
    reprise: bool,

    /// Render album-cover.pdf: the flat cover sheet for --profil, back cover
    /// then spine then front, at 300 dpi. The spine and the bleed both come
    /// from the profile, so the same album gives a different sheet at each
    /// supplier.
    #[arg(long)]
    cover: bool,

    /// Preflight the album already built in --out against a printer profile:
    /// resolution, pagination, bleed, colour space, fonts, safe zone. Prints
    /// the report plus the spec sheet. Exits non-zero on a blocking defect.
    #[arg(long)]
    prevol: bool,

    /// Printer profile the export and the preflight read: cloudprinter,
    /// prodigi, lulu, generique.
    #[arg(long, default_value = "cloudprinter", value_name = "ID")]
    profil: String,

    /// List the printer profiles and exit
    #[arg(long)]
    profils: bool,

    /// The same profiles as JSON, whole. Feeds the dev album server, which
    /// stands in for the Tauri commands when the destination screen is
    /// worked on in a browser.
    #[arg(long, hide = true)]
    profils_json: bool,

    /// Write one PDF per template into DIR, slots filled with the check
    /// palette. Feeds the PDF → PNG raster non-regression.
    #[arg(long, value_name = "DIR", hide = true)]
    sheets: Option<PathBuf>,

    /// Print the caption proposed for spread PLANCHE (1-based) of the album
    /// in --out, as JSON: a string, or null when silence is the answer.
    /// Feeds the dev album server, like --profils-json.
    #[arg(long, value_name = "PLANCHE", hide = true)]
    proposition: Option<usize>,

    /// Print the templates a spread holding SRCS (a JSON array of photo
    /// sources, in slot order) can switch to, count and orientation both
    /// fitting, as a JSON array of names. Feeds the dev album server, like
    /// --proposition; the srcs travel so an unsaved edit filters right.
    #[arg(long, value_name = "SRCS", hide = true)]
    gabarits: Option<String>,

    /// Run the generated-template bench over composed album directories
    /// (grouped into reference sets by their source folder) and print the
    /// verdict as JSON: which enumerated combinations are green on every
    /// set. Feeds `gabarit::RETENUS` through scripts/banc-gabarits.sh.
    #[arg(long, value_name = "DIRS", num_args = 1.., hide = true)]
    banc_gabarits: Vec<PathBuf>,
}

/// Built once at startup so `--help` can show the format table.
static FORMAT_HELP: std::sync::LazyLock<String> = std::sync::LazyLock::new(|| {
    format!("Formats de page :\n{}\n\nOu une taille libre, par exemple --format 240x180.", format::help())
});

/// The printer profile behind `--profil`, or a message naming the way out.
fn profil(id: &str) -> Result<&'static colophon_core::printer::PrinterProfile> {
    colophon_core::printer::PrinterProfile::par_id(id)
        .ok_or_else(|| anyhow::anyhow!("profil inconnu : {id} (voir --profils)"))
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    if cli.formats {
        println!("{}", format::help());
        return Ok(());
    }

    let trim = format::parse(&cli.format)?;

    // Toute commande qui travaille sur un dossier d'album existant le migre
    // d'abord. Un `focal` d'avant le schéma 2 ne veut plus ce qu'il dit :
    // l'auditer, l'imprimer, le reprendre ou en tirer une scène sans migrer
    // rendrait un verdict sur un autre recadrage que celui qui est réglé.
    // Un dossier neuf n'a pas d'album.json, et un album déjà au schéma
    // courant ressort sans être réécrit — la migration s'arrête avant.
    if cli.out.join("album.json").exists() {
        let _ = colophon_core::build::migrate_album_folder(&cli.out);
    }

    if cli.dump_geometry {
        let mut album = Album::new("geometry", std::path::Path::new("."), trim);
        album.bleed_mm = cli.bleed;
        println!("{}", serde_json::to_string_pretty(&pdf::dump_geometry(&album))?);
        return Ok(());
    }

    if let Some(chemin) = &cli.dump_scene {
        let path = if chemin.is_empty() {
            cli.out.join("album.json")
        } else {
            PathBuf::from(chemin)
        };
        let json = std::fs::read_to_string(&path)
            .with_context(|| format!("lecture de {}", path.display()))?;
        let mut album: Album = serde_json::from_str(&json).context("album.json illisible")?;
        // The page shape comes from --format, so the same committed album
        // yields the six geometries the parity check walks.
        album.trim_mm = trim;
        println!(
            "{}",
            serde_json::to_string_pretty(&colophon_core::scene::album(&album))?
        );
        return Ok(());
    }

    if let Some(dir) = &cli.sheets {
        let album = Album::new("gabarits", std::path::Path::new("."), trim);
        let files = pdf::render_template_sheets(&album, dir)?;
        eprintln!("{} gabarits rendus dans {}", files.len(), dir.display());
        return Ok(());
    }

    if cli.audit {
        let report = colophon_core::audit::audit(&cli.out)?;
        println!("{}", serde_json::to_string_pretty(&report)?);
        if !report.ok {
            std::process::exit(1);
        }
        return Ok(());
    }

    if cli.profils {
        for p in colophon_core::printer::PrinterProfile::tous() {
            println!("{:<14} {}", p.id, p.nom);
        }
        return Ok(());
    }

    if cli.profils_json {
        println!(
            "{}",
            serde_json::to_string(colophon_core::printer::PrinterProfile::tous())?
        );
        return Ok(());
    }

    if let Some(planche) = cli.proposition {
        let album: Album = serde_json::from_str(&std::fs::read_to_string(
            cli.out.join("album.json"),
        )?)?;
        let p = planche
            .checked_sub(1)
            .and_then(|i| colophon_core::legende::proposition(&album, i));
        println!("{}", serde_json::to_string(&p)?);
        return Ok(());
    }

    if let Some(srcs) = &cli.gabarits {
        let srcs: Vec<String> =
            serde_json::from_str(srcs).context("--gabarits attend un tableau JSON de src")?;
        let noms = colophon_core::gabarit::compatibles_srcs(&cli.out, &srcs)?;
        println!("{}", serde_json::to_string(&noms)?);
        return Ok(());
    }

    if !cli.banc_gabarits.is_empty() {
        let t0 = std::time::Instant::now();
        let rapport =
            colophon_core::banc::banc(&cli.banc_gabarits, &|line| eprintln!("{line}"))?;
        eprintln!(
            "banc en {:.1?} : {} candidats, {} verts, {} recalés, {} sans essai, {} jeu manquant",
            t0.elapsed(),
            rapport.candidats,
            rapport.verts.len(),
            rapport.recales,
            rapport.sans_essai,
            rapport.jeu_manquant
        );
        println!("{}", serde_json::to_string_pretty(&rapport)?);
        return Ok(());
    }

    if cli.prevol {
        let report = colophon_core::prevol::prevol(&cli.out, profil(&cli.profil)?)?;
        println!("{}", serde_json::to_string_pretty(&report)?);
        if !report.ok {
            std::process::exit(1);
        }
        return Ok(());
    }

    if cli.reprise {
        let report = colophon_core::reprise::reprise(&cli.out)?;
        println!("{}", serde_json::to_string_pretty(&report)?);
        if !report.ok {
            std::process::exit(1);
        }
        return Ok(());
    }

    if cli.cover {
        let profil = profil(&cli.profil)?;
        let t0 = std::time::Instant::now();
        let out = colophon_core::cover::render_cover_pdf(
            &cli.out,
            profil,
            &cli.out.join("album-cover.pdf"),
        )?;
        // The sheet's own dimensions, printed rather than left to be guessed:
        // this is the number that gets checked against the supplier's template.
        let album: Album = serde_json::from_str(&std::fs::read_to_string(
            cli.out.join("album.json"),
        )?)?;
        let g = colophon_core::cover::geometry(&album, profil);
        eprintln!(
            "done in {:.1?}: {} ({:.1} × {:.1} mm, dos {:.1} mm, fond perdu {:.1} mm)",
            t0.elapsed(),
            out.display(),
            g.media_w,
            g.media_h,
            g.spine_mm(),
            g.bleed_ext
        );
        return Ok(());
    }

    if cli.print {
        // The profile decides whether the cover rides in this file, so
        // --print now answers to --profil like --cover and --prevol do.
        let profil = profil(&cli.profil)?;
        let t0 = std::time::Instant::now();
        let out = colophon_core::render_print_pdf(
            &cli.out,
            profil,
            &cli.out.join("album-print.pdf"),
            &|line| eprintln!("{line}"),
            &|| false,
        )?;
        eprintln!("done in {:.1?}: {} ({})", t0.elapsed(), out.display(), profil.nom);
        return Ok(());
    }

    let densite = colophon_core::layout::Densite::par_id(&cli.densite).ok_or_else(|| {
        anyhow::anyhow!(
            "densité inconnue : {} (aeree, equilibree, dense)",
            cli.densite
        )
    })?;
    // The two halves of a composition, each reachable on its own: dump what
    // the photographs say, or compose from what they said. Neither replaces
    // the plain path below, which still runs both in a row.
    if let Some(fichier) = &cli.dump_fiches {
        let photos = cli.photos.clone().expect("clap enforces this");
        let t0 = std::time::Instant::now();
        let releve = colophon_core::build::releve(
            &photos,
            &cli.out,
            &BuildOptions {
                progress: Box::new(|line| eprintln!("{line}")),
                ..Default::default()
            },
        )?;
        releve.ecrire(fichier)?;
        // The weight is reported rather than fought: a versioned file nobody
        // can read at a glance has lost half its point, so if it ever grows
        // past a megabyte that is a decision to take, not one to hide behind
        // a compressor.
        let ko = std::fs::metadata(fichier).map(|m| m.len()).unwrap_or(0) as f64 / 1024.0;
        eprintln!(
            "done in {:.1?}: {} ({} fiches, {} illisibles, {ko:.0} Ko)",
            t0.elapsed(),
            fichier.display(),
            releve.photos.len(),
            releve.illisibles.len()
        );
        return Ok(());
    }

    if let Some(fichier) = &cli.depuis_fiches {
        let releve = colophon_core::Releve::lire(fichier)?;
        // What the folder held, said once by the only path that has no other
        // way of saying it: the scan is not run here, its counts travel.
        eprintln!(
            "relevé : {} fiches, {} illisibles, {} HEIC et {} fichiers inconnus \
             écartés au scan",
            releve.photos.len(),
            releve.illisibles.len(),
            releve.skipped_heic,
            releve.skipped_other
        );
        let t0 = std::time::Instant::now();
        let report = colophon_core::build::composer(
            releve,
            &cli.out,
            BuildOptions {
                title: cli.title.clone(),
                spreads: cli.spreads,
                trim,
                densite,
                progress: Box::new(|line| eprintln!("{line}")),
                variantes: if cli.variantes {
                    colophon_core::build::variantes_offertes(densite, cli.spreads.max(8))
                } else {
                    Vec::new()
                },
                ..Default::default()
            },
        )?;
        eprintln!("done in {:.1?}: {}", t0.elapsed(), report.album_json.display());
        return Ok(());
    }

    let photos = cli.photos.clone().expect("clap enforces this");
    let t0 = std::time::Instant::now();

    let report = build_album(
        &photos,
        &cli.out,
        BuildOptions {
            title: cli.title.clone(),
            spreads: cli.spreads,
            trim,
            densite,
            progress: Box::new(|line| eprintln!("{line}")),
            variantes: if cli.variantes {
                colophon_core::build::variantes_offertes(densite, cli.spreads.max(8))
            } else {
                Vec::new()
            },
            ..Default::default()
        },
    )?;

    eprintln!(
        "done in {:.1?}: {} and {}",
        t0.elapsed(),
        report.album_json.display(),
        report.album_pdf.expect("le chemin complet rend un PDF").display()
    );
    Ok(())
}
